artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  destination_folder: artifacts/data_ingestion/data
  filename: samsum
  miscellaneous_folder: artifacts/data_ingestion/miscellaneous

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum
  model_checkpoint: google/pegasus-cnn_dailymail
