artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  destination_folder: artifacts/data_ingestion/data
  filename: samsum
  miscellaneous_folder: artifacts/data_ingestion/miscellaneous

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_transformation
  destination_path: artifacts/data_preprocessing/preprocessed_data
  tokenizer_name: google/pegasus-cnn_dailymail
